name: desk360flutter
description: Desk360 Flutter SDK
version: 1.1.0
homepage:

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  event_bus: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.teknasyon.desk360flutter
        pluginClass: Desk360flutterPlugin
      ios:
        pluginClass: Desk360flutterPlugin
